### ISSUE TITLE
Enabling cachalot causes NoReverseMatch

### ISSUE THREAD

**Issue by andyhasit** [noripyt/django-cachalot#109]
I had cachalot installed and added, with no errors, but it turns out it wasn't being applied, so I set this in the settings:

```
CACHALOT_DATABASES = ['default']
```
And now I'm getting NoReverseMatch in certain templates... Commenting that line out brings everything back to normal. How could this be?

**Comment by BertrandBordage** [comment]
Hum, weird, could you give more detail please?
- Which versions of Django and django-cachalot are you using?
- Are you using a CMS, like django CMS?
- Are you using the django-cachalot debug toolbar panel?
- What is the name and arguments of the view that couldn’t be reversed?

**Comment by BertrandBordage** [comment]
Closing for now because of the lack of info.
