### ISSUE TITLE
Can't pickle memoryview objects [2]

### ISSUE THREAD

**Issue by scherbakovx** [noripyt/django-cachalot#125]
I suppose it's same as https://github.com/noripyt/django-cachalot/issues/115
My setup is:

- Python 3.6.5
- Django 2.1.5
- django-cachalot 2.1.0
- djangorestframework 3.8.2
- Postgres 10.3, PostGIS 2.4

The error appeared after migrating from Django 1.11 to 2.1

![Sentry stacktrace](https://user-images.githubusercontent.com/9437117/52050374-6cdd2b00-2561-11e9-93f3-75d98be8ad3e.png)

**Comment by josh-stableprice** [comment]
Django core seems to deal with this by casting directly to bytes. Is this something that should be done here?

**Comment by josh-stableprice** [comment]
Core talks about their changes here: https://code.djangoproject.com/ticket/30294

**Comment by apie** [comment]
We resolved this problem by writing a custom Pickler which handles memoryview objects by casting them to bytes and providing this as an option to Memcached:

```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache', 'LOCATION': ['127.0.0.1:11211'],
        'OPTIONS': {'pickler': Mypickler}
```
NB: I see you are using the Redis backend. It should work similarly.

**Comment by apie** [comment]
Our pickler:
```
from django.core.cache.backends.memcached import pickle


def make_bytes(obj):
    if isinstance(obj, (tuple, list)):
        return obj.__class__(make_bytes(o) for o in obj)
    if isinstance(obj, dict):
        return {k: make_bytes(v) for k, v in obj.items()}
    if isinstance(obj, memoryview):
        return bytes(obj)
    return obj


class Mypickler(pickle.Pickler):
    def dump(self, obj):
        try:
            super().dump(obj)
        except TypeError:
            obj = make_bytes(obj)
            super().dump(obj)
```

**Comment by abodacs** [comment]
@apie 
Thanks for the snippet and I think you missed a return before  super().dump(obj)
should be ` return super().dump(obj)` Right?

**Comment by apie** [comment]
@abodacs No, return is not needed there.

Actually, a while after I posted my message we found out about https://docs.python.org/3/library/copyreg.html#copyreg.pickle and we now use that instead of a custom pickler:

in `mysite/myapp/__init__.py`
```
default_app_config = 'mysite.myapp.appconfig.Config'
```
and in `mysite/myapp/appconfig.py`
```
import copyreg
from django.apps import AppConfig


class Config(AppConfig):
    name = 'mysite.myapp'

    def ready(self):
        # https://docs.python.org/3/library/copyreg.html#copyreg.pickle
        copyreg.pickle(memoryview, lambda val: (memoryview, (bytes(val),)))
```

**Comment by jayvdb** [comment]
Worth noting that copyreg is exactly what is done in https://github.com/Suor/django-cacheops/blob/4d43f8868299b5ddc7f9ddbebbd23d639a718343/cacheops/query.py#L591

**Comment by Andrew-Chen-Wang** [comment]
Can't believe I just saw this thread. Cachalot doesn't support GIS in its tests, but I can definitely add this pickle lambda so that this issue isn't raised again. Thanks for the code!

**Comment by jayvdb** [comment]
commits
https://github.com/Suor/django-cacheops/commit/f1ae887dc932bcaf8202872594ddf3be097881cb
https://github.com/Suor/django-cacheops/commit/db3b6795354f84ad8328882d0484c45e203e0976

Unfortunately no direct tests there to be replicated.  Just pickling a memoryview shouldnt be too hard.  https://github.com/python/cpython/blob/master/Lib/test/test_picklebuffer.py#L18 probably has some tests that can be lifted out easily.
