### ISSUE TITLE
TypeError when trying to invalidate a model

### ISSUE THREAD

**Issue by Silvester23** [noripyt/django-cachalot#129]
I am trying to invalidate the cache for a model in the `__init__` of the corresponding ModelAdmin, using `invalidate(DummyModel)`.

This leads to the following error:

`File ".../cachalottest/admin.py", line 11, in __init__
    invalidate(DummyModel)
  File ".../lib/python3.6/site-packages/cachalot/api.py", line 80, in invalidate
    _invalidate_tables(cache, db_alias, tables)
  File ".../lib/python3.6/site-packages/cachalot/utils.py", line 197, in _invalidate_tables
    {get_table_cache_key(db_alias, t): now for t in tables},
  File ".../lib/python3.6/site-packages/cachalot/utils.py", line 197, in <dictcomp>
    {get_table_cache_key(db_alias, t): now for t in tables},
TypeError: 'str' object is not callable
`

The problem seems to be that the cachalot settings have not been loaded at that point and just return the string representation of `cachalot_settings.CACHALOT_TABLE_KEYGEN` instead of the function. Calling `cachalot_settings.load()` before `invalidate` fixes the issue but seems like an unnecessary workaround.

**Comment by BertrandBordage** [comment]
Mmm, specifying code with side effects in the `__init__` of a `ModelAdmin` is not a good practice.
If you want something to happen when you load an application, use [the `ready` method of an `AppConfig`](https://docs.djangoproject.com/en/2.2/ref/applications/#django.apps.AppConfig.ready).

You cannot expect django-cachalot API to work before the models are fully loaded, and they are not fully loaded when `ModelAdmin`s are instantiated.
