### ISSUE TITLE
Cache invalidation not working properly for multiple cache servers for the same database

### ISSUE THREAD

**Issue by vinodpandey** [noripyt/django-cachalot#133]
Setup:
```
Python==3.6.0
Django==1.11.18
python-memcached==1.59
django-cachalot==2.1.0
```

Architecture:
```
5 django servers with each having it's own cache (memcached)
MySQL
```

Below cache invalidation script is used to invalidate cache in all 5 servers
```
import threading

from cachalot.api import invalidate
from cachalot.signals import post_invalidation
from django.dispatch import receiver
from django.conf import settings

SIGNAL_INFO = threading.local()

@receiver(post_invalidation)
def invalidate_other_caches(sender, **kwargs):
    if getattr(SIGNAL_INFO, 'was_called', False):
        return
    db_alias = kwargs['db_alias']
    for cache_alias in settings.CACHES:
        if cache_alias == settings.CACHALOT_CACHE:
            continue
        SIGNAL_INFO.was_called = True
        try:
            invalidate(sender, db_alias=db_alias, cache_alias=cache_alias)
        finally:
            SIGNAL_INFO.was_called = False
```

Other settings
```
CACHALOT_CACHE = 'default'
CACHES contains 'default' as localhost and rest 4 servers as 's1', 's2', 's3', 's4'
```

Issue:
When a model is updated, the cache is not getting invalidated properly in rest of the servers. But when below command is run from django python shell from original server, the cache gets invalidated in all the servers. Although, in below command, we have specified only one server.

```
invalidate('test_generator_header', db_alias='default', cache_alias='api1')
```

The same setup is working fine in python 2.7 with below configuration with proper cache invalidation for all servers. 

```
Python==2.7.16
Django==1.11.18
python-memcached==1.57
django-cachalot==1.3.0
```
Cache invalidation script, CACHALOT_CACHE and CACHES field values are same.

**Comment by vinodpandey** [comment]
Adding new observations:

In python 2.7 with below configuration cache invalidation is working correctly for all server

```sh
Python==2.7.16
Django==1.11.18
python-memcached==1.57
django-cachalot==1.3.0
MySQL-python==1.2.5
```

whereas, the issue starts re-occurring in python 2.7 too when `MySQL-python` is replaced with `mysqlclient==1.4.6`

```sh
Python==2.7.16
Django==1.11.18
python-memcached==1.57
django-cachalot==1.3.0
mysqlclient==1.4.6
```

**Comment by Andrew-Chen-Wang** [comment]
@vinodpandey Thanks for updating. We've upgraded Django-cachalot to version 2.2.0 and I've yet to drop support for Python 2.7, so do you mind upgrading and running your test cases again?

On the side note, at first, I thought you might've configured your cache settings incorrectly. With your new observation, I'm not so sure anymore since I don't use MySQL. (I had rough times setting it up). I'm also somewhat confused with your threading usage. I'd much rather have you use async tasks using celery + redis. I usually develop with docker in mind at cookiecutter-django if that helps in setup.

**Comment by vinodpandey** [comment]
@Andrew-Chen-Wang thanks for your help. The issue is resolved now. It was occurring because of how I was importing the configuration file which contained the CACHES setting. 

We are using [this pattern](https://django-cachalot.readthedocs.io/en/latest/limits.html#multiple-cache-servers-for-the-same-database ) of multiple cache servers for same database where we created a settings_local.py file with CACHES containing dict of all other caches.

The import worked fine in python2.7, but in python3.6 the import was not working and CACHES contained the default value only.

```
worked fine in python 2.7 >> from settings_local import *  
for python3.6 this had to be updated to >> from settings.settings_local import * 

We were catching the exception and not logging it anywhere. 
This made it difficult to debug and find the root cause.

###################################
# settings_local.py file for cache server setting to be used by django-cachalot
###################################
try:
    from settings.settings_local import * 
except ImportError:
    pass

```
