### ISSUE TITLE
Running pip install the installed django version should not be modified.

### ISSUE THREAD

**Issue by fabiocaccamo** [noripyt/django-cachalot#134]
Running `pip install django-cachalot` on a project with `django==2.2.3`, django is uninstalled and an older django version in installed (because `django-cachalot` doesn't support django 2.2 yet).

**I think that the installed django version should no be modified by any 3rd party package.**

**Comment by ritiko** [comment]
I think you might be using some sort of package manager e.g. `pipenv` to experience this. `django-cachalot` doesn't technically alter the django version, it just specifies a low dependency as seen here: https://github.com/noripyt/django-cachalot/blob/master/requirements.txt

There's a PR trying to make it django 2.2 compatible: https://github.com/noripyt/django-cachalot/pull/127

If you use a package manager, I'd recommend setting a lower limit for your django installation before installing additional packages.

I recommend `pipenv` with which you could do something like `pipenv install django>=2.2` to make sure that any packages that can't meet this requirement (like django-cachalot in this case) will not be installable.

**Comment by Andrew-Chen-Wang** [comment]
@ritiko Removed dependency max for Django in latest package release 2.2.0
