### ISSUE TITLE
Invalidating doesn't seem to work for Subquery

### ISSUE THREAD

**Issue by ghost** [noripyt/django-cachalot#137]
I have somewhat convoluted query set with two subqueries that I use to annotate main query. Caching seems to work fine but when I add new record to models subqueries are touching it does not get invalidated and presents stale results.

My QS code is:
```
B_count = (
    B.objects.filter(some_field__pk=OuterRef("pk"))
    .order_by()
    .values("some_field__pk")
    .annotate(c=Count("*"))
    .values("c")
)

A_count = (
    A.objects.filter(
        B__field__pk=OuterRef("pk"),
        user=self.request.user,
        [more filters]
    )
    .order_by()
    .values("B__field__pk")
    .annotate(c=Count("*"))
    .values("c")
)

return C.objects.filter(pk__in=[my_list]).annotate(
    B_count=Coalesce(Subquery(B_count), 0),
    A_count=Coalesce(
        Subquery(A_count, output_field=IntegerField()), 0
    ),
)
```

When I add records to `A` or `B` results of my `C` query do not get invalidated.

**Comment by Andrew-Chen-Wang** [comment]
Sorry, in the latest tests, I've been seeing a lot of errors regarding invalidation in general. Fixing now at #146

**Comment by Andrew-Chen-Wang** [comment]
Should be fixed as of latest.
