### ISSUE TITLE
Need help in CachalotPanel

### ISSUE THREAD

**Issue by ierosodin** [noripyt/django-cachalot#138]
I used MemcachedCache as my cached backend, and I also checked If it worked.
(by using ```watch -td '(echo stats ; echo quit) | nc 127.0.0.1 11211 | grep get_hits '``` to check if cached hit and cached miss was happened)

However, I doubted that most of the cache is caused by my site's content, not the hit of database, so I tried to use debug_toolbar to see whether if the cachalot was working.

For the cachalot part,
I set ```'cachalot',``` in INSTALLED_APPS, and ```CACHALOT_TIMEOUT = 21600```.

For the debug part,
I set ```DEBUG_TOOLBAR_PANELS = ["debug_toolbar.panels.cache.CachePanel", "cachalot.panels.CachalotPanel"]```.

I found that cachalotpanel is totaly empty!

Can you give me some advice how to make it work?
Thanks

Sincerely,
Tony

**Comment by Andrew-Chen-Wang** [comment]
@ierosodin Can you let me know what Django version, OS, Database/backend, and python version you're using? That'll help a bit. In the meantime, try pip installing jinja2 and see if that helps and lemme know results.

**Comment by ierosodin** [comment]
Hi,
Glad that we have a new maintainer~~~
These are the version of tools I use:
---------------------------------------
Django: 2.1.15
Python: 3.7.5
cachalot: Cachalot 2.1.0
debug_toolbar:Debug Toolbar 2.2
OS: ubuntu 18.04.2
cache backend: MemcachedCache (pymemcache)
---------------------------------------
My action is caching the query and result when user asks for the data at the first time.
And then, when another user hits the same query, I want to know whether if it works.
The situation is after the page is loaded, debug panel won't change anymore (SQL part and Cache part only have the result of loading page), and the Cachalot part has nothing.

Thanks!
Sincerely,
Tony

**Comment by Andrew-Chen-Wang** [comment]
Hey @ierosodin Took me awhile to figure out why this is happening. Django debug toolbar JUST removed process_response in their latest release, 2.2 (can be found in the panels.py of cachalot). I'm working on the fix right now.

**Comment by Andrew-Chen-Wang** [comment]
So the temporary fix is to downgrade Django debug toolbar to <2.2 to keep using CachalotPanel. I'm not sure when I can fix the panel since... well I keep getting the same errors when I change process_response to process_request. Anyhow, that's the temporary fix. I'll close this issue when I commit a working method.

**Comment by ierosodin** [comment]
I see. I'll downgrade it first.
Thanks!

**Comment by Andrew-Chen-Wang** [comment]
@ierosodin I've published the package. You can upgrade cachalot and django debug toolbar.
