### ISSUE TITLE
Cached queries not being invalidated during testing only

### ISSUE THREAD

**Issue by jpclark6** [noripyt/django-cachalot#143]
We have been using cachalot for a long time without any issues, but we're currently updating to Django 2.2 from 1.11 and a lot of tests started failing. The cached values aren't being updated including things like .count() that should be working. Everything works correctly in our staging environment so it seems isolated to testing. Has anyone else seen this after upgrading to Django 2+ or have a way to fix it?

Basic case inside a test:
```
(Pdb) self.customer1.items.all().count()
0
(Pdb) n
-> True [Updated items. Should now be 1]
(Pdb) self.customer1.items.all().count()
0
(Pdb) self.customer1.items.all()
<QuerySet [<Item: 3>]>
(Pdb) len(self.customer1.items.all())
1
```

**Comment by Andrew-Chen-Wang** [comment]
@jpclark6 I'm currently fixing the Travis testing and I did notice, occasionally, that the invalidation is taking awhile (it's also failing some tests). However, could you retry but this time using Django-debug-toolbar==2.1.x (Don't use 2.2) and add cachalot's debug toolbar? A couple of screenshots of the SQL, the cache, and the cachalot along with the results of your few queries.

If we can deduce where the issue stems from (invalidation drains my soul...), then we can implement a performance improvement to cachalot.

**Comment by Andrew-Chen-Wang** [comment]
@jpclark6 I've updated the package with updated tests. Django 2.2 broke a bunch of test configurations. Again, a couple screenshots from django debug toolbar would be helpful.

If you upgrade to Django 3.0, you could see some improvements as the number of SQL statements decreases across the board.

**Comment by Andrew-Chen-Wang** [comment]
Marking this as stale. I've tried to make Django 2.2 more compatible in the latest minor release.
