### ISSUE TITLE
Slack invite link is not valid anymore + CACHALOT_ONLY_CACHABLE_TABLES seems to not work

### ISSUE THREAD

**Issue by faridelnasire** [noripyt/django-cachalot#148]
I've tried setting the CACHALOT_ONLY_CACHABLE_TABLES setting to this:
```CACHALOT_ONLY_CACHABLE_TABLES = frozenset(('discussion_question',))```
Which ends up actually completely disabling caching. I've double-checked the table name, it is in fact `discussion_question`. Am I setting the wrong value?

Tried joining the Slack workspace, but it looks expired.

**Comment by Andrew-Chen-Wang** [comment]
I noticed the invite link was broken too. Will fix it when I get the time this week. Outbreak added a lot of workload.
You have an extra parenthesis. I don’t believe you have to use a frozenset btw. A tuple or set should work too.

**Comment by faridelnasire** [comment]
Just wanted to update and close this ticket, it ended up being an error on my end:
Using the debug toolbar I discovered the query I was running was touching more tables than I had initially thought. After adding those tables to the tuple as well, it worked as expected.
