### ISSUE TITLE
Slack invite link expired

### ISSUE THREAD

**Issue by valentijnscholten** [noripyt/django-cachalot#152]
## Question
Is there still a Cachalot Slack channel/workspace? If yes, the invite link in the README has expired :-)

**Comment by Andrew-Chen-Wang** [comment]
Whoops, I updated the first Slack link but forgot about the second. @valentijnscholten

**Comment by valentijnscholten** [comment]
Thanks, there is another old one :-)
https://github.com/noripyt/django-cachalot/blob/master/docs/reporting.rst
