### ISSUE TITLE
Support for Django 3.1

### ISSUE THREAD

**Issue by cfobel** [noripyt/django-cachalot#162]
## Description

Add support for Django 3.1

## Rationale

Django 3.1 adds new features, including:

 - [async views and middleware support][0]
 - cross-database [JSON field][1]

[0]: https://docs.djangoproject.com/en/3.1/releases/3.1/#asynchronous-views-and-middleware-support
[1]: https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.JSONField

## Known issues

Not currently compatible with [Django 3.1][2] due to:

> The compatibility imports of `django.core.exceptions.EmptyResultSet` in `django.db.models.query`, `django.db.models.sql`, and `django.db.models.sql.datastructures` are removed.

After monkey-patching `django.db.models.query` to re-add `EmptyResultSet`, I encounter the following error:

> ```
>  SystemCheckError: System check identified some issues:
> 
>  ERRORS:
>  ?: (cachalot.E003) Django 3.1 is not compatible with this version of django-cachalot.
>        HINT: Refer to the django-cachalot documentation to find which versions are compatible.
> 
> ```

[2]: https://docs.djangoproject.com/en/3.1/releases/3.1/#id1

**Comment by Andrew-Chen-Wang** [comment]
Hi, yes it is not currently compatible. If you’re testing Django 3.1 this
early, use Django’s setting for SILENCED_SYSTEM_CHECKS. I’ll ping you once
I find the time to get full support for Django 3.1.

Also, thank you for showing me the errors!

**Comment by Andrew-Chen-Wang** [comment]
@cfobel If my branch's CI is good to go, expect a new patch version of cachalot in an hour from now. Thanks for updating me on Django 3.1! I didn't realize they'd push it out this early.

**Comment by cfobel** [comment]
@Andrew-Chen-Wang, thank you so much for jumping on this so quickly! I am amazed!! I also want to say thanks for such a great library. After spending a lot of time trying to get performance improvements via judicious use of `select_related()`, `prefetch_related()`, and tinkering with other caching mechanisms, I am really impressed with the performance improvements achieved using `cachalot`; and with almost no configuration!

> Django 3.1 has a LOT more changes that just randomly appeared in my tox test... Maybe wait one more day.

No problem at all! No particular rush on my end, as I'm not blocked by it at the moment. I have some plans to make use of some Django 3.1 features, but nothing immediate.

**Comment by Andrew-Chen-Wang** [comment]
@cfobel Django31 branch passed. Finished with dinner, I'll push the new version. With that being said, I'ma close this issue. Thanks for letting me know so early on!

**Comment by cfobel** [comment]
Thanks so much! Sorry, I just saw your responses buried in my Gmail "Updates".

I really appreciate you taking the time to update this. Cheers! 🎉
