### ISSUE TITLE
Get AttributeError: 'str' object has no attribute 'tzinfo' when serialize data.

### ISSUE THREAD

**Issue by thanhpd-teko** [noripyt/django-cachalot#168]
## What happened?

Hi, i got error "AttributeError: 'str' object has no attribute 'tzinfo'" when serialize data.
Not sure but may be come from serialize date time field.
```
created_at = models.DateTimeField(editable=False)
updated_at = models.DateTimeField(editable=False)

```
Data on redis:
"2020-11-27T09:24:46.762816",
 "2020-11-27T09:24:46.762816",
Please help.

Django==2.2.4
django-cachalot==2.3.3

**Comment by Andrew-Chen-Wang** [comment]
Are you using MySQL? If so, MySQL doesn't support it, but if you're using any other database, cachalot should be able to support it. Here's our test case for time zone enabled datetime objects in your models: https://github.com/noripyt/django-cachalot/blob/d0b5213014e80db2ecb78cbf0474e791414d53d8/cachalot/tests/read.py#L265-L273

Some traceback and/or code would be helpful since I'm not sure where this is actually erroring and if it's actually a cachalot error. But [datetime objects should be fine](https://github.com/noripyt/django-cachalot/blob/d0b5213014e80db2ecb78cbf0474e791414d53d8/cachalot/utils.py#L26-L29). If I recall correctly, you have to enable `USE_TZ` in [your settings](https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-USE_TZ).

**Comment by thanhpd-teko** [comment]
I have already enabled USE_TZ in app. 
`
ppm_1                | 2020-11-27 16:51:38 | ERROR | 497 | 139625689626368 | base.py:160 | 'str' object has no attribute 'tzinfo'
ppm_1                | Traceback (most recent call last):
ppm_1                |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
ppm_1                |     response = handler(request, *args, **kwargs)
ppm_1                |   File "/opt/project/ppm_core/views/health.py", line 34, in get
ppm_1                |     data = UserSerializer(users, many=True).data
ppm_1                |   File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 765, in data
ppm_1                |     ret = super(ListSerializer, self).data
ppm_1                |   File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 262, in data
ppm_1                |     self._data = self.to_representation(self.instance)
ppm_1                |   File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 683, in to_representation
ppm_1                |     self.child.to_representation(item) for item in iterable
ppm_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
ppm_1                |     self._fetch_all()
ppm_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
ppm_1                |     self._result_cache = list(self._iterable_class(self))
ppm_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 72, in __iter__
ppm_1                |     for row in compiler.results_iter(results):
ppm_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1044, in apply_converters
ppm_1                |     value = converter(value, expression, connection)
ppm_1                |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/operations.py", line 254, in convert_datetimefield_value
ppm_1                |     value = timezone.make_aware(value, self.connection.timezone)
ppm_1                |   File "/usr/local/lib/python3.7/site-packages/django/utils/timezone.py", line 270, in make_aware
ppm_1                |     return timezone.localize(value, is_dst=is_dst)
ppm_1                |   File "/usr/local/lib/python3.7/site-packages/pytz/__init__.py", line 244, in localize
ppm_1                |     if dt.tzinfo is not None:
ppm_1                | AttributeError: 'str' object has no attribute 'tzinfo'
`

The exception comes from this function:
    def normalize(self, dt, is_dst=False):
        '''Correct the timezone information on the given datetime'''
        if dt.tzinfo is self:
            return dt
        if dt.tzinfo is None:
            raise ValueError('Naive time - no tzinfo set')
        return dt.astimezone(self)
The dt object type is string, has no tzinfor field then exception occured.
@Andrew-Chen-Wang please help.

**Comment by Andrew-Chen-Wang** [comment]
Like I said, you're using MySQL. You need to set `USE_TZ=False`

**Comment by thanhpd-teko** [comment]
Yeah, thanks.

**Comment by Andrew-Chen-Wang** [comment]
Good luck!
