### ISSUE TITLE
Unable to use django-cachalot with django-tenants

### ISSUE THREAD

**Issue by nitinnain** [noripyt/django-cachalot#172]
Trying to setup django-cachalot on a [django-tenants](https://github.com/django-tenants/) project and it reports this right at the start:

    (cachalot.W003) Database engine 'django_tenants.postgresql_backend' is not supported by django-cachalot.
    HINT: Switch to a supported database engine.

Any tips on fixing this?

**Comment by jcass77** [comment]
Have a look at #123. It hasn't been rebased on the main branch for a while but should give you a fair idea.

The trick is to have cachalot generate a unique cache key for each tenant (see `get_multi_tenant_table_cache_key` for details).

**Comment by nitinnain** [comment]
Thanks John!
