### ISSUE TITLE
Django and Cachalot Support Different Backends for Memcached

### ISSUE THREAD

**Issue by jjorissen52** [noripyt/django-cachalot#179]
## Description
Django [supports](https://docs.djangoproject.com/en/dev/topics/cache/#memcached) `pymemcache` (or `pylibmc`) as its Memcached backend. However, `cachalot` supports `python-memcached` (and also `pylibmc`). I think it makes sense to support the same backends as Django.

[//]: # (Describe what you are implementing and how, if possible)

## Rationale
Having Django and django-cachalot supporting different backends could lead to a painful situation where Django is not working with `python-memcached` but django-cachalot is not working with `pymemcache`, which would cause developers to choose between outdated versions of libraries, implementing multiple backends for their cache, or forking the project.

**Comment by Andrew-Chen-Wang** [comment]
In the middle of finals. If you can, it'd be great if a PR was made that included test cases and re-configured tox.

**Comment by jjorissen52** [comment]
It appears that this happened in the transition from Django 3.1 to 3.2:
```
- the two supported by Django are pylibmc and pymemcache.
+ the two most common are python-memcached and pylibmc.
```

I will close this in favor of #175 and #180.

**Comment by Andrew-Chen-Wang** [comment]
@jjorissen52 this will be implemented in the next release. AFAIK based on my dev environment, it's looking good. Thanks for letting me know of this!
