### ISSUE TITLE
Please include docs in sdist

### ISSUE THREAD

**Issue by Natureshadow** [noripyt/django-cachalot#201]
In order to include documentation in the Debian package, please include the `docs/` directory in the sdist tarball.

Thanks,
Nik

**Comment by Andrew-Chen-Wang** [comment]
@Natureshadow think it's fine 👍 In any case, we should probably change from MANIFEST.in to `package_data` in setup.py if you want to get that goin. Not entirely sure how to separate the included files for bdist_wheel. So again, PR welcome!
