### ISSUE TITLE
Django 4.0 Support

### ISSUE THREAD

**Issue by moshfrid** [noripyt/django-cachalot#207]
Django 4.0 stable just came out and support would be awesome!

**Comment by Andrew-Chen-Wang** [comment]
@moshfrid prep for a patch release in 20 minutes. PR is set; note, there doesn't seem to be any changes as we test the main branch every day. You can view the successful result here tested against our current master: https://github.com/noripyt/django-cachalot/actions/runs/1547587268

**Comment by moshfrid** [comment]
Wow that was quick! I can confirm as I ran my full test suite and everything passed.
