### ISSUE TITLE
Reduce number of unnecessary table invalidations

### ISSUE THREAD

**Issue by JanoValaska** [noripyt/django-cachalot#212]
## Description

[//]: # (What are you proposing and how would we implement it?)
First of all thank you very much for this great framework, we have been using it for many years and it served us well.

However during our recent efforts to increase speed of our system we noticed that in some situations django-cachalot performs unnecessary table invalidations after SELECT SQL statements.

### Problematic situation
Many models in our system have DateTimeFields which track when model instance was created and updated. We name these fields "created_at" and "updated_at". When retrieving objects from the database, Django's ORM performs SELECT SQL statement behind the scenes  - e.g. for our models with "created_at" and "updated_at" DateTimeFields the statement will look like this:

`
 'SELECT some_field_name, some_other_field_name, created_at, updated_at from some_table_name;'
`

This SELECT SQL statement should not invalidate "some_table_name" table, because SELECT SQL statement does not change data in "some_table_name" table, but combination of "in" operator in this [block of code](https://github.com/noripyt/django-cachalot/blob/master/cachalot/monkey_patch.py#L136-L138) and our field names "created_at" and "updated" trigger unnecessary "some_table_name" table invalidation.

```
'create' in 'SELECT some_field_name, some_other_field_name, created_at, updated_at from some_table_name;' # is True
'update' in 'SELECT some_field_name, some_other_field_name, created_at, updated_at from some_table_name;' # is True
````

### Proposed solution
To get rid of this issue I propose to use "startswith" string method instead of "in" operator. The problematic block of code would look like this after the fix:

```
                    if sql.startswith('update') or sql.startswith('insert') or sql.startswith('delete') \
                            or sql.startswith('alter') or sql.startswith('create') \
                            or sql.startswith('drop'):
``` 

## Rationale

[//]: # (Why should this be implemented?)

These unnecessary table invalidations make table with field name that contains any of these SQL keywords('update', 'insert', 'delete', 'alter', 'create', 'drop') effectively uncacheable, because table is invalidated by all types of SQL statements.  

Please let me know if the issue I described is valid and if proposed solution sounds correct. Thank you and keep up the good work.

**Comment by Andrew-Chen-Wang** [comment]
This is a great catch! Please make a PR!

**Comment by JanoValaska** [comment]
Before we move on with this I would like to double check that any of those keywords ('update', 'insert', 'delete', 'alter', 'create', 'drop') can be present in the middle of the sql statement. 

Maybe the safest solution would be to do something like this:

```
                    if 'update ' in sql or 'insert ' in sql or 'delete ' in sql \
                            or 'alter ' in sql or 'create ' in sql \
                            or 'drop ' in sql:
```

or use elegant regex instead of this hairy condition.

```
                    if re.search(r"(update\s|insert\s|delete\s|alter\s|create\s|drop\s)", sql):
```

Which solution do you think is the best?

**Comment by Andrew-Chen-Wang** [comment]
As far as I’m aware, they are not used in subqueries. Create the PR and see if the test suite passes. We can ask online on SO then move forward
________________________________

**Comment by BertrandBordage** [comment]
For info, common table expressions come before a query, like`WITH cte AS (…) INSERT INTO …`, so `.startswith` cannot be used.

I suggest using a regular expression, but please compile it in a global variable, as regexps are slow compared to `in` (which is why I chose `in` originally). This should do it:
```python
import re

SQL_DATA_CHANGE_RE = re.compile(
    '|'.join([
        fr'(\W|\A){re.escape(keyword)}(\W|\Z)'
        for keyword in ['update', 'insert', 'delete', 'alter', 'create', 'drop']
    ]),
    flags=re.IGNORECASE,
)
SQL_DATA_CHANGE_RE.search('update')  # Matches
SQL_DATA_CHANGE_RE.search('updated')  # Doesn’t match
SQL_DATA_CHANGE_RE.search(' update ')  # Matches
SQL_DATA_CHANGE_RE.search('update_')  # Doesn’t match
SQL_DATA_CHANGE_RE.search('update-')  # Matches, but I guess that’s a good tradeoff as it can only match values, that are not supposed to be passed as literals in the query, they have to be passed in params.
```

**Comment by JanoValaska** [comment]
PR created - https://github.com/noripyt/django-cachalot/pull/213
