### ISSUE TITLE
Does not support Django 4.1

### ISSUE THREAD

**Issue by danjac** [noripyt/django-cachalot#217]
## What happened?

Incompatibility between django-cachalot and django 4.1 on install:

```
  Because django-cachalot (2.5.1) depends on Django (>=2.2,<4.1)
   and no versions of django-cachalot match >2.5.1,<3.0.0, django-cachalot (>=2.5.1,<3.0.0) requires Django (>=2.2,<4.1).
 ```

## What should've happened instead?

`django-cachalot` installed

## Steps to reproduce

* django 4.1
* python 3.10
* django-cachalot 2.5.1
* poetry

```
poetry add django-cachalot
```

**Comment by Andrew-Chen-Wang** [comment]
thanks everyone sit tight; will begin adding 4.1 to CI tonight

**Comment by dmkoch** [comment]
@Andrew-Chen-Wang I created a PR with the 4.1 changes. The test suites pass in my fork: https://github.com/dmkoch/django-cachalot/pull/1

**Comment by Andrew-Chen-Wang** [comment]
thanks so much @dmkoch left a comment in your fork
