### ISSUE TITLE
Allow enum-likes in CACHABLE_PARAM_TYPES

### ISSUE THREAD

**Issue by rythm-of-the-red-man** [noripyt/django-cachalot#218]
## Description
Currently, Django's `TextChoices` property `__class__` indicates it's enum-like 
```python
>>> class MockTextChoices(models.TextChoices):
...     foo="foo"
...     bar="bar"
... 
>>> MockTextChoices.foo
MockTextChoices.foo
>>> MockTextChoices.foo.__class__
<enum 'MockTextChoices'>
```
And it's perfectly fine to do something like this, when constructing queryset:
```python
queryset.filter(
            Q(
                mock__in=(
                    MockTextChoices.foo,
                    MockTextChoices.bar
                )
            )
        )
```
Yet, such query, even if valid, can't be cached. It happens because value under `MockTextChoices.foo.__class__` is not present in `CACHABLE_PARAM_TYPES`, which is used in `check_parameter_types` method. So long story short it will throw `UncachableQuery` and make db call anyway.

If you replace `MockTextChoices.foo` with `"foo"` or `MockTextChoices.foo.value` it works just fine for obv reasons.
[//]: # (What are you proposing and how would we implement it?)
My suggestion would be to modify `check_parameter_types` to allow syntax above. I don't know right away how to implement that, but I'll have a thought, and I'll edit this ticket with proposed answer :^)

## Rationale

[//]: # (Why should this be implemented?)
I think such behavior might lead to unexpected queries, that are hard to catch without debug toolbar and pure luck lol.  I mean, if Django accepts such syntax as valid query django-cachalot should be able to cache it right? 👀

**Comment by Andrew-Chen-Wang** [comment]
Good enhancement/bug, thanks!

> pure luck lol

Yea it sucks. Having debug toolbar helps a lot to know which queries were actually cached or not
