### ISSUE TITLE
ReadTheDocs isn't building

### ISSUE THREAD

**Issue by danlamanna** [noripyt/django-cachalot#265]
https://django-cachalot.readthedocs.io/en/latest/index.html doesn't reflect the latest version of master.

Note for instance, https://django-cachalot.readthedocs.io/en/latest/quickstart.html#settings is missing `CACHALOT_FINAL_SQL_CHECK` which is present in the source (https://github.com/noripyt/django-cachalot/blob/master/docs/quickstart.rst#cachalot_final_sql_check).

**Comment by zachmullen** [comment]
The last time the RTD build succeeded appears to be this commit:

```
commit fe08ef3d28dce96b80b2506b9d4ee1c7aadbe608 (HEAD)
Author: Andrew Chen Wang <60190294+Andrew-Chen-Wang@users.noreply.github.com>
Date:   Mon May 24 22:46:24 2021 -0400
```

I was able to build docs on latest master locally with no issues.

@Andrew-Chen-Wang I have some experience debugging RTD builds; if you can post the RTD error log I may be able to create a PR to fix it.

**Comment by Andrew-Chen-Wang** [comment]
Hi all, thanks for reporting this and apologies for being so late. I've resolved this; the unfortunate part is that the fix probably isn't retroactive (?) but latest is now up to date.
