### ISSUE TITLE
CACHALOT_FINAL_SQL_CHECK=True fails for ResolvedOuterRef

### ISSUE THREAD

**Issue by sdolemelipone** [noripyt/django-cachalot#268]
## What happened?

When running with `CACHALOT_FINAL_SQL_CHECK=True`, evaluation of query containing nested `OuterRef`s due to multiple subqueries raises the error:
```
ValueError: This queryset contains a reference to an outer query and may only be used in a subquery.
```
which originates from `ResolvedOuterRef.as_sql()` in `django.db.models.expressions` [here](https://github.com/django/django/blob/39de2e97a06d0317973b280bc159ca6f89fc64e3/django/db/models/expressions.py#L929).

No error is raised when running with `CACHALOT_FINAL_SQL_CHECK=False`

## What should've happened instead?

Ideally no error raised, or a warning that the SQL check can't be completed?

## Steps to reproduce
Here's a dumb example with the model from the cachalot's test framework (but usually these would be different models with more useful subqueries):

```python
from django.db.models import OuterRef, Subquery
from cachalot.tests.models import Test

def check_nested_outerref():
    test_instance = Test(name="foo")

    subquery2 = Test.objects.filter(id=OuterRef(OuterRef(OuterRef("id"))))

    subquery1 = Test.objects.annotate(
        public_from_subquery2=Subquery(subquery2.values("public")[:1])
    )

    Test.objects.annotate(
        public_from_subquery1=Subquery(subquery1.values("public_from_subquery2")[:1])
    ).get(pk=test_instance.pk)
```

[//]: # (Include host configuration: OS, Django version, database, etc.)

**Comment by Andrew-Chen-Wang** [comment]
Fun. When running with the flag off, it's working properly? Also which Django version are you on? There's a potential the latest version may have quirks I'm unaware of since the internal ORM has changed a lot.

**Comment by sdolemelipone** [comment]
Thanks for replying so quickly. This is with Django 5.1.1, Python 3.12. I did a quick test with the `main` branch of django and the problem is present there as well.

Sorry, I'm going to need to improve the example in steps to reproduce. The one I've given here fails with the flag on **and** off.

In my project codebase I have an example which only fails with the flag on - which is how I found the bug, by setting `CACHALOT_FINAL_SQL_CHECK=True` for the project and watching the errors roll in.

I'll work on updating the example so that it only fails when the flag is on.

**Comment by sdolemelipone** [comment]
@Andrew-Chen-Wang apologies, there isn't a bug with cachalot here, it was actually my code. The `OuterRef(OuterRef(OuterRef(...)))` was being referenced in two of the subqueries, one of which only need **two** nested calls, not three.

The example I gave causes the same error message, but in that case because there's one call to OuterRef too many, which I mistook for the same underlying problem.

So turning on `CACHALOT_FINAL_SQL_CHECK` actually found a bug in my code (just a really obscure one that didn't show up until this!)
